name: ING

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and Push Docker image
      run: |
        docker build -t ${{ secrets.AZURE_CONTAINER_REGISTRY }}/myapp:latest .
        echo ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }} | docker login ${{ secrets.AZURE_CONTAINER_REGISTRY }} -u ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }} --password-stdin
        docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}/myapp:latest

    - name: Deploy to Azure Container Apps
      uses: azure/container-apps-deploy-action@v2
      with:
        appSourcePath: .
        registryUrl: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
        imageToDeploy: ${{ secrets.AZURE_CONTAINER_REGISTRY }}/myapp:latest
        resourceGroup: ${{ secrets.AZURE_RESOURCE_GROUP }}
        containerAppName: ${{ secrets.AZURE_CONTAINER_APP_NAME }}
        location: ${{ secrets.AZURE_REGION }}
